package bank;

import java.awt.Color;
import java.awt.Frame;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.ResultSetMetaData;
import java.util.regex.PatternSyntaxException;
import javax.swing.RowFilter;
import libraries.Bank;

/**
 *
 * @author MAMOY BOOTSTRAP
 */
public class ViewBank extends javax.swing.JInternalFrame implements MouseListener {
    
    Bank bankLib = new Bank();
    private boolean selected = false;
    private int bankId;

    /**
     * Creates new form Bank
     */
    public ViewBank() {
        initComponents();
        setCaptureDataTable();
        loadTableData();
        setBankId(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBank = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTextFieldCode = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonNew = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Bank List");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTableBank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableBank.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTableBankComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBank);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(614, 30));
        jPanel3.setLayout(new java.awt.GridLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Search : ");
        jPanel4.add(jLabel2, java.awt.BorderLayout.LINE_START);

        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyReleased(evt);
            }
        });
        jPanel4.add(jTextFieldSearch, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setLayout(new java.awt.GridLayout(0, 1));
        jPanel9.add(jTextFieldCode);
        jPanel9.add(jTextFieldName);
        jPanel9.add(jTextFieldAddress);

        jPanel11.setPreferredSize(new java.awt.Dimension(568, 20));
        jPanel11.setLayout(new java.awt.GridLayout());
        jPanel11.add(jLabel5);
        jPanel11.add(jLabel6);
        jPanel11.add(jLabel7);

        jButtonNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Add-icon.png"))); // NOI18N
        jButtonNew.setText("New");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });
        jPanel11.add(jButtonNew);

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save-icon.png"))); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel11.add(jButtonSave);

        jPanel9.add(jPanel11);

        jPanel8.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel10.setPreferredSize(new java.awt.Dimension(50, 100));
        jPanel10.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Code:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel10.add(jLabel1);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Name: ");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel10.add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Address: ");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel10.add(jLabel4);
        jPanel10.add(jLabel8);

        jPanel8.add(jPanel10, java.awt.BorderLayout.LINE_START);

        getContentPane().add(jPanel8, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyReleased
        search();
    }//GEN-LAST:event_jTextFieldSearchKeyReleased

    private void jTableBankComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTableBankComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableBankComponentShown

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        saveBankInfo();
        newData();
        loadTableData();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        newData();
    }//GEN-LAST:event_jButtonNewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBank;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
public static DefaultTableModel clientList = new DefaultTableModel() {
        public boolean isCellEditable(int row, int col) {
            if (col < 0) {
                return false;
            } else {
//                return true;
                return false;
            }
        }
    };
//end of Instantiation
    final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(clientList);
    //---End of Tables coloum and row handling--------------------------------------------------//
    //

    private void setCaptureDataTable() {
        String[] columnName = {
            "id",
            "CODE",
            "NAME",
            "ADDRESS",};
        
        jTableBank = new javax.swing.JTable(clientList);
        jTableBank.setRowSorter(sorter);
        jTableBank.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        jTableBank.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTableBank.setRowSelectionAllowed(true);
        jTableBank.getTableHeader().setReorderingAllowed(false);
        jTableBank.setBackground(Color.getHSBColor(180, 244, 217));
        JTableHeader header = jTableBank.getTableHeader();
        jTableBank.addMouseListener(this);
        header.setBackground(Color.black);
        header.setForeground(Color.blue);
        header.setFont(new java.awt.Font("Tahoma", 1, 11));
        jScrollPane1.setViewportView(jTableBank);
        
        for (int i = 0; i < columnName.length; i++) {
            clientList.addColumn(columnName[i]);
        }

        //...Set column width of the table
        TableColumn[] column = new TableColumn[200];
        //...
        column[0] = jTableBank.getColumnModel().getColumn(0);
        column[0].setPreferredWidth(0);
        
        column[1] = jTableBank.getColumnModel().getColumn(1);
        column[1].setPreferredWidth(100);
        
        column[2] = jTableBank.getColumnModel().getColumn(2);
        column[2].setPreferredWidth(180);
        
        column[3] = jTableBank.getColumnModel().getColumn(3);
        column[3].setPreferredWidth(180);
        
        TableColumn hidden = jTableBank.getColumnModel().getColumn(0);
        hidden.setMinWidth(0);
        hidden.setPreferredWidth(0);
        hidden.setMaxWidth(0);
    }
    
    private void loadTableData() {
        clientList.setRowCount(0);
        bankLib.selectAll();
        for (int i = 0; i < bankLib.getData().size(); i++) {
            clientList.addRow((Vector) bankLib.getData().get(i));
        }
    }
    
    private void saveBankInfo() {
        String bankCode = jTextFieldCode.getText().toString().trim();
        String bankName = jTextFieldName.getText().toString().trim();
        String bankAddress = jTextFieldAddress.getText().toString().trim();
        
        bankLib.setCode(bankCode);
        bankLib.setName(bankName);
        bankLib.setAddress(bankAddress);
        bankLib.setActive(true);
        if (this.isSelected() == false) {
            bankLib.insert();
            JOptionPane.showMessageDialog(this, "Bank Information Saved");
        } else {
            bankLib.update();
            JOptionPane.showMessageDialog(this, "Bank Information Updated");
        }
    }
    
    private void search() {
        String text = this.jTextFieldSearch.getText();
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            try {
                sorter.setRowFilter(
                        RowFilter.regexFilter("(?i)" + text, 2));
            } catch (PatternSyntaxException pse) {
                System.err.println("Bad regex pattern");
            }
        }
    }
    
    @Override
    public void mouseClicked(MouseEvent e) {
        if (e.getClickCount() == 2) {
            setSelected(true);
            String idl = jTableBank.getValueAt(jTableBank.getSelectedRow(), 0).toString().trim();
            String codel = jTableBank.getValueAt(jTableBank.getSelectedRow(), 1).toString().trim();
            String namel = jTableBank.getValueAt(jTableBank.getSelectedRow(), 2).toString().trim();
            String addressl = jTableBank.getValueAt(jTableBank.getSelectedRow(), 3).toString().trim();
            
            bankLib.setId(Integer.parseInt(idl));
            jTextFieldCode.setText(codel);
            jTextFieldName.setText(namel);
            jTextFieldAddress.setText(addressl);
        }
    }
    
    private void newData() {
        setBankId(0);
        jTextFieldCode.setText("");
        jTextFieldName.setText("");
        jTextFieldAddress.setText("");
        this.setSelected(false);
    }
    
    @Override
    public void mousePressed(MouseEvent e) {
        
    }
    
    @Override
    public void mouseReleased(MouseEvent e) {
        
    }
    
    @Override
    public void mouseEntered(MouseEvent e) {
        
    }
    
    @Override
    public void mouseExited(MouseEvent e) {
        
    }

    /**
     * @return the selected
     */
    public boolean isSelected() {
        return selected;
    }

    /**
     * @param selected the selected to set
     */
    public void setSelected(boolean selected) {
        this.selected = selected;
    }

    /**
     * @return the bankId
     */
    public int getBankId() {
        return bankId;
    }

    /**
     * @param bankId the bankId to set
     */
    public void setBankId(int bankId) {
        this.bankId = bankId;
    }
    
}
