/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loans;

import client.AddEditClient;
import dbconn.DBConnection;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Frame;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import libraries.Loan;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import org.joda.time.LocalDate;
import org.joda.time.Period;
import org.joda.time.PeriodType;
import reports.NewReportDialog;

/**
 *
 * @author Lancepyro
 */
public class NewJLoanFrame extends javax.swing.JInternalFrame implements MouseListener {

    Loan loanLib = new Loan();
    private int clientId;
    private JasperPrint print = new JasperPrint();

    /**
     * Creates new form NewJLoanFrame
     */
    public NewJLoanFrame() {
        initComponents();
        setCaptureDataTable();
        loadTableData();
        setClientId(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogPrint = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDateChooserDateFrom = new com.toedter.calendar.JDateChooser();
        jDateChooserDateTo = new com.toedter.calendar.JDateChooser();
        jComboBoxBranch = new javax.swing.JComboBox();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientList = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jDialogPrint.setTitle("Print Report");

        jLabel1.setText("Branch: ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel2.setText("Date From: ");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setText("Date To: ");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDateChooserDateFrom.setDateFormatString("yyyy-M-d");

        jDateChooserDateTo.setDateFormatString("yyyy-M-d");

        jComboBoxBranch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matina" }));

        javax.swing.GroupLayout jDialogPrintLayout = new javax.swing.GroupLayout(jDialogPrint.getContentPane());
        jDialogPrint.getContentPane().setLayout(jDialogPrintLayout);
        jDialogPrintLayout.setHorizontalGroup(
            jDialogPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPrintLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxBranch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooserDateFrom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogPrintLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jDateChooserDateTo, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialogPrintLayout.setVerticalGroup(
            jDialogPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPrintLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialogPrintLayout.createSequentialGroup()
                        .addGroup(jDialogPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jDateChooserDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(jDateChooserDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuItem1.setText("View");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Print Voucher");
        jPopupMenu1.add(jMenuItem2);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Loans");
        setToolTipText("");

        jPanel8.setLayout(new java.awt.BorderLayout());

        jTableClientList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableClientList.setColumnSelectionAllowed(true);
        jTableClientList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jTableClientList);

        jPanel8.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setMaximumSize(new java.awt.Dimension(100, 50));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(394, 40));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel9.setPreferredSize(new java.awt.Dimension(98, 20));
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Add-icon.png"))); // NOI18N
        jButtonAdd.setMnemonic('A');
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonAdd);

        jButtonEdit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sync.png"))); // NOI18N
        jButtonEdit.setMnemonic('E');
        jButtonEdit.setText("Reload");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonEdit);

        jButtonPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/print-icon.png"))); // NOI18N
        jButtonPrint.setMnemonic('P');
        jButtonPrint.setText("Print");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonPrint);

        jPanel1.add(jPanel9);

        jPanel3.setPreferredSize(new java.awt.Dimension(98, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(98, 20));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(98, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);

        jPanel7.setPreferredSize(new java.awt.Dimension(98, 20));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7);

        jPanel6.setPreferredSize(new java.awt.Dimension(98, 20));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jTextFieldSearch.setMinimumSize(new java.awt.Dimension(50, 20));
        jTextFieldSearch.setPreferredSize(new java.awt.Dimension(59, 20));
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyPressed(evt);
            }
        });
        jPanel6.add(jTextFieldSearch, java.awt.BorderLayout.CENTER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Zoom-icon.png"))); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel6);

        jPanel8.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel8, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        addEditLoan(getClientId());
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        loadTableData();
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jTextFieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyPressed
        search();
    }//GEN-LAST:event_jTextFieldSearchKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        search();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        this.jDialogPrint.show();
        this.jDialogPrint.setLocationRelativeTo(this);
        this.jDialogPrint.setSize(385, 170);
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        disp();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        addEditLoan(getClientId());
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JComboBox jComboBoxBranch;
    private com.toedter.calendar.JDateChooser jDateChooserDateFrom;
    private com.toedter.calendar.JDateChooser jDateChooserDateTo;
    private javax.swing.JDialog jDialogPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientList;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
public static DefaultTableModel clientList = new DefaultTableModel() {

    };
//end of Instantiation
    final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(clientList);
    //---End of Tables coloum and row handling--------------------------------------------------//
    //

    private void setCaptureDataTable() {
        String[] columnName = {
            "id",
            "CLIENT ID",
            "FULL NAME",
            "PN NO.",
            "DATE",
            "LOAN TYPE",
            "MONTHLY AMORTIZATION",
            "MONTHLY CHANGE",
            "LOAN TERM",
            "GROSS LOAN"
        };

        jTableClientList = new javax.swing.JTable(clientList);
        jTableClientList.setRowSorter(sorter);
        jTableClientList.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        jTableClientList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTableClientList.setRowSelectionAllowed(true);
        jTableClientList.getTableHeader().setReorderingAllowed(false);
        jTableClientList.setBackground(Color.getHSBColor(180, 244, 217));
        JTableHeader header = jTableClientList.getTableHeader();
        jTableClientList.addMouseListener(this);
        header.setBackground(Color.black);
        header.setForeground(Color.blue);
        header.setFont(new java.awt.Font("Tahoma", 1, 11));
        jScrollPane1.setViewportView(jTableClientList);

        for (int i = 0; i < columnName.length; i++) {
            clientList.addColumn(columnName[i]);
        }

        //...Set column width of the table
        TableColumn[] column = new TableColumn[200];
        //...
        column[0] = jTableClientList.getColumnModel().getColumn(0);
        column[0].setPreferredWidth(0);

        column[1] = jTableClientList.getColumnModel().getColumn(1);
        column[1].setPreferredWidth(100);

        column[2] = jTableClientList.getColumnModel().getColumn(2);
        column[2].setPreferredWidth(180);

        column[3] = jTableClientList.getColumnModel().getColumn(3);
        column[3].setPreferredWidth(180);

        column[4] = jTableClientList.getColumnModel().getColumn(4);
        column[4].setPreferredWidth(180);

        column[5] = jTableClientList.getColumnModel().getColumn(5);
        column[5].setPreferredWidth(180);

        column[6] = jTableClientList.getColumnModel().getColumn(6);
        column[6].setPreferredWidth(180);

        column[7] = jTableClientList.getColumnModel().getColumn(7);
        column[7].setPreferredWidth(180);

        column[8] = jTableClientList.getColumnModel().getColumn(8);
        column[8].setPreferredWidth(180);

        column[9] = jTableClientList.getColumnModel().getColumn(9);
        column[9].setPreferredWidth(180);

        TableColumn hidden = jTableClientList.getColumnModel().getColumn(0);
        hidden.setMinWidth(0);
        hidden.setPreferredWidth(0);
        hidden.setMaxWidth(0);

        TableColumn hidden1 = jTableClientList.getColumnModel().getColumn(1);
        hidden1.setMinWidth(0);
        hidden1.setPreferredWidth(0);
        hidden1.setMaxWidth(0);
    }

    private void loadTableData() {
        clientList.setRowCount(0);
        loanLib.selectAllLoans();
        for (int i = 0; i < loanLib.getData().size(); i++) {
            clientList.addRow((Vector) loanLib.getData().get(i));
        }
    }

    private void search() {
        String text = this.jTextFieldSearch.getText();
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            try {
                sorter.setRowFilter(
                        RowFilter.regexFilter("(?i)" + text, 2));
            } catch (PatternSyntaxException pse) {
                System.err.println("Bad regex pattern");
            }
        }
    }

    private void addEditLoan(int id) {
        try {
            NewLoanApplicationDialog newLoan = new NewLoanApplicationDialog((Frame) getDesktopPane().getTopLevelAncestor(), true, id);
            newLoan.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void disp() {

        //create report
        try {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            print = printMethod();
            NewReportDialog reportDialog = new NewReportDialog(javax.swing.JOptionPane.getFrameForComponent(this), true, printMethod(), "Member List");
            reportDialog.setSize(900, 700);
            reportDialog.setLocationRelativeTo(this);
            reportDialog.setVisible(true);
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        } catch (Exception e) {
            e.printStackTrace();
        }
        //end
    }

    public JasperPrint printMethod() {
        JasperPrint localPrintVar = null;
        try {
            System.out.println("Filling Report.......");
            Map map = new HashMap();
            map.put("dateFrom", ((JTextField) jDateChooserDateFrom.getDateEditor().getUiComponent()).getText());
            map.put("dateTo", ((JTextField) jDateChooserDateTo.getDateEditor().getUiComponent()).getText());
            map.put("Branch", jComboBoxBranch.getSelectedItem().toString());
            localPrintVar = JasperFillManager.fillReport(System.getProperty("user.dir") + "/src/reports/loanlist.jasper", map, DBConnection.conn);
            System.out.println("Done!");
        } catch (Exception e) {
            e.printStackTrace();
        }
        return localPrintVar;
    }

    @Override
    public void mouseClicked(MouseEvent e) {

    }

    @Override
    public void mousePressed(MouseEvent e) {

    }

    @Override
    public void mouseReleased(MouseEvent e) {
        if (e.isPopupTrigger()) {
            jPopupMenu1.show(e.getComponent(), e.getX(), e.getY());
            int selectedId = Integer.parseInt(jTableClientList.getValueAt(jTableClientList.getSelectedRow(), 0).toString());
            this.setClientId(selectedId);
        }
    }

    @Override
    public void mouseEntered(MouseEvent e) {

    }

    @Override
    public void mouseExited(MouseEvent e) {

    }

    /**
     * @return the clientId
     */
    public int getClientId() {
        return clientId;
    }

    /**
     * @param clientId the clientId to set
     */
    public void setClientId(int clientId) {
        this.clientId = clientId;
    }
}
